Repository wecode-bootcamp-korea/33-2nd-MegaBoxu-backend, pull requests merged in 2022-06, with the labels that each got.

#2 Add : Modeling
  cores/__init__.py
  cores/admin.py
  cores/apps.py
  cores/migrations/__init__.py
  cores/models.py
  cores/tests.py
  cores/views.py
  megaboxu/settings.py
  movies/__init__.py
  movies/admin.py
  movies/apps.py
  movies/migrations/0001_initial.py
  movies/migrations/0002_alter_movie_poster_url.py
  movies/migrations/__init__.py
  movies/models.py
  movies/tests.py
  movies/views.py
  reservations/__init__.py
  reservations/admin.py
  reservations/apps.py
  reservations/migrations/0001_initial.py
  reservations/migrations/__init__.py
  reservations/models.py
  reservations/tests.py
  reservations/views.py
  reviews/__init__.py
  reviews/admin.py
  reviews/apps.py
  reviews/migrations/0001_initial.py
  reviews/migrations/0002_alter_review_unique_together_review_unique_review.py
  reviews/migrations/__init__.py
  reviews/models.py
  reviews/tests.py
  reviews/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: 멘토 리뷰 요청

#3 Add : MovieListView
  megaboxu/urls.py
  movies/tests.py
  movies/urls.py
  movies/views.py
Labels: 수정 요청

#4 Add : Setting to ORM Optimize
  megaboxu/settings.py
Labels: 멘토 리뷰 요청

#5 Add : MovieDetailView
  movies/tests.py
  movies/urls.py
  movies/views.py
Labels: 멘토 리뷰 요청

#6 Modify : Movie Models
  movies/migrations/0003_alter_movie_age_limit_alter_movie_reservation_rate_and_more.py
  movies/models.py
  reservations/urls.py
Labels: 멘토 리뷰 요청

#7 Add : RegionTheaterListView, MovieTheaterView
  megaboxu/urls.py
  movies/views.py
  reservations/models.py
  reservations/tests.py
  reservations/urls.py
  reservations/views.py
Labels: Conflict 해결 요청

#9 Modify : MovieListView
  movies/views.py
Labels: 멘토 리뷰 요청

#8 [소셜 로그인] 카카오 로그인
  megaboxu/settings.py
  megaboxu/urls.py
  movies/views.py
  requirements.txt
  reservations/views.py
  reviews/urls.py
  reviews/views.py
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: 멘토 리뷰 요청

#10 수정 : 카카오 로그인
  megaboxu/urls.py
  users/views.py
Labels: 멘토 리뷰 요청
